#! /bin/sh

### BEGIN INIT INFO
# Provides:          nala-ws
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Nala.Service.Web
# Description:       Nala front-end service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting nala-ws "
    # example 1 - system service
    /usr/bin/mono-service /usr/share/services/nala-ws/Nala.Service.Web.exe
    # example 2 - run script as user
    # su --login mkaz --command "/home/mkaz/bin/my-script --cmd-args"
    ;;
  stop)
    echo "Stopping nala-ws"
    kill `cat /tmp/Nala.Service.Web.exe.lock`
    ;;
  restart|reload|condrestart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/nala-ws {start|stop}"
    exit 1
    ;;
esac

exit 0
